DROP TABLE IF EXISTS `members`;
CREATE TABLE IF NOT EXISTS `members` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `CSMId` varchar(500) DEFAULT NULL,
  `BanglaName` varchar(500) DEFAULT NULL,
  `name` varchar(500) DEFAULT NULL,
  `FatherName` varchar(500) DEFAULT NULL,
  `MotherName` varchar(500) DEFAULT NULL,
  `HusbandWifeName` varchar(500) DEFAULT NULL,
  `Age` varchar(500) DEFAULT NULL,
  `Occupation` varchar(500) DEFAULT NULL,
  `Nationality` varchar(500) DEFAULT NULL,
  `NId` varchar(500) DEFAULT NULL,
  `PassportNo` varchar(500) DEFAULT NULL,
  `TaxIdNo` varchar(500) DEFAULT NULL,
  `Phone` varchar(500) DEFAULT NULL,
  `Mobile` varchar(500) DEFAULT NULL,
  `PresentVillageName` varchar(500) DEFAULT NULL,
  `PresentPostOffice` varchar(500) DEFAULT NULL,
  `PresentUpojela` varchar(500) DEFAULT NULL, 
  `PresentJela` varchar(500) DEFAULT NULL,
  `SPName` varchar(500) DEFAULT NULL,
  `SPName2` varchar(500) DEFAULT NULL,
  `SPFatherName` varchar(500) DEFAULT NULL,
  `SPFatherName2` varchar(500) DEFAULT NULL,
  `SPMotherName` varchar(500) DEFAULT NULL,
  `SPMotherName2` varchar(500) DEFAULT NULL,
  `SPHusbanWifeName` varchar(500) DEFAULT NULL,
  `SPHusbanWifeName2` varchar(500) DEFAULT NULL,
  `Relation` varchar(500) DEFAULT NULL,
  `RElation2` varchar(500) DEFAULT NULL,
  `GivenPortion` varchar(500) DEFAULT NULL,
  `GivenPortion2` varchar(500) DEFAULT NULL,
  `Image` varchar(500) DEFAULT NULL,
  `TMSSIdCard` varchar(500) DEFAULT NULL,
  `NIdImage` varchar(500) DEFAULT NULL,
  `NomineeImage` varchar(500) DEFAULT NULL,
  `BirthCertificate` varchar(500) DEFAULT NULL,
  `NomineeImage2` varchar(500) DEFAULT NULL,
  `BirthCertificate2` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  FULLTEXT KEY `idx_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;